# Generated by Django 5.2.7 on 2026-05-15 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0003_pessoa_autorizacao_uso_imagem_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('object_id', models.UUIDField(verbose_name='id do objeto')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificada', 'Falta justificada'), ('em_transito', 'Em trânsito / parcial')], default='presente', max_length=15, verbose_name='status')),
                ('forma', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], default='presencial', max_length=12, verbose_name='forma de participação')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo da entidade')),
                ('municipio', models.ForeignKey(blank=True, help_text='Município vinculado à pessoa no momento do registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas', to='cadastro.municipio', verbose_name='município (snapshot)')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='cadastro.pessoa', verbose_name='pessoa')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'presença',
                'verbose_name_plural': 'presenças',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='presenca_pr_content_666e69_idx')],
                'unique_together': {('pessoa', 'content_type', 'object_id')},
            },
        ),
    ]
