# Generated by Django 5.2.7 on 2026-05-18 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_envolvimentopauta_arquivado_em_and_more'),
        ('presenca', '0002_presenca_arquivado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivado_em', models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em')),
                ('nome_visitante', models.CharField(help_text='Preenchido manualmente quando o visitante não tem cadastro.', max_length=255, verbose_name='nome do visitante')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('organizacao', models.CharField(blank=True, help_text='Empresa, prefeitura, secretaria etc.', max_length=255, verbose_name='organização/cargo')),
                ('motivo', models.CharField(choices=[('reuniao', 'Reunião agendada'), ('evento', 'Participar de evento/atividade'), ('entrega', 'Entrega de documento'), ('tecnico', 'Atendimento técnico'), ('institucional', 'Visita institucional'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='motivo')),
                ('pessoa_recebida_por', models.CharField(blank=True, help_text='Quem na FNP irá atender (livre — ex.: "Eq. Presidência").', max_length=255, verbose_name='recebido(a) por')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('chegou_em', models.DateTimeField(auto_now_add=True, verbose_name='chegou em')),
                ('saiu_em', models.DateTimeField(blank=True, null=True, verbose_name='saiu em')),
                ('municipio', models.ForeignKey(blank=True, help_text='Município que o visitante representa (se aplicável).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='cadastro.municipio')),
                ('pessoa', models.ForeignKey(blank=True, help_text='Vincular a uma pessoa cadastrada se já existir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='cadastro.pessoa')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'visita à FNP',
                'verbose_name_plural': 'visitas à FNP',
                'ordering': ['-chegou_em'],
                'indexes': [models.Index(fields=['-chegou_em'], name='presenca_vi_chegou__a15ba3_idx'), models.Index(fields=['pessoa'], name='presenca_vi_pessoa__b93de2_idx')],
            },
        ),
    ]
