# Generated by Django 5.2.7 on 2026-05-20 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0003_visita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto da pessoa visitando (webcam local ou enviada via pré-credenciamento).', null=True, upload_to='visitas/%Y/%m/', verbose_name='foto de credenciamento'),
        ),
        migrations.AddField(
            model_name='visita',
            name='pre_credenciado',
            field=models.BooleanField(default=False, help_text='True se a foto/dados vieram de um link enviado antes da visita.', verbose_name='veio pré-credenciado?'),
        ),
        migrations.CreateModel(
            name='CredenciamentoPrevio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivado_em', models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em')),
                ('token', models.CharField(help_text='Slug aleatorio usado na URL publica. Expira em 30 dias.', max_length=64, unique=True, verbose_name='token publico')),
                ('nome_visitante', models.CharField(max_length=255, verbose_name='nome do visitante')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('organizacao', models.CharField(blank=True, max_length=255, verbose_name='organização/cargo')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='motivo da visita')),
                ('data_visita_prevista', models.DateField(blank=True, null=True, verbose_name='data prevista da visita')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='credenciamentos/%Y/%m/', verbose_name='foto enviada pelo visitante')),
                ('documentos_aceitos', models.BooleanField(default=False, help_text='Aceite do tratamento de imagem para credenciamento.', verbose_name='aceitou termos LGPD?')),
                ('status', models.CharField(choices=[('pendente', 'Pendente (link enviado)'), ('preenchido', 'Preenchido (aguardando chegada)'), ('utilizado', 'Utilizado (visitou)'), ('expirado', 'Expirado')], default='pendente', max_length=12, verbose_name='status')),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credenciamentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('visita_gerada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_pre_credenciamento', to='presenca.visita')),
            ],
            options={
                'verbose_name': 'pré-credenciamento',
                'verbose_name_plural': 'pré-credenciamentos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['token'], name='presenca_cr_token_e49d01_idx'), models.Index(fields=['status', '-criado_em'], name='presenca_cr_status_9312ae_idx')],
            },
        ),
    ]
