# Generated by Django 5.2.7 on 2026-05-20 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('presenca', '0004_visita_foto_visita_pre_credenciado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciamentoprevio',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='tipo da entidade de origem'),
        ),
        migrations.AddField(
            model_name='credenciamentoprevio',
            name='object_id',
            field=models.UUIDField(blank=True, help_text='Vincula o pré-credenciamento ao evento/atividade/missão que motivou o convite.', null=True, verbose_name='id do objeto de origem'),
        ),
        migrations.AddIndex(
            model_name='credenciamentoprevio',
            index=models.Index(fields=['content_type', 'object_id'], name='presenca_cr_content_08fcfa_idx'),
        ),
    ]
