# Generated by Django 5.2.7 on 2026-05-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0005_credenciamentoprevio_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciamentoprevio',
            name='face_embedding',
            field=models.JSONField(blank=True, default=list, help_text='Vetor de 128 floats extraído da foto enviada pelo visitante.', verbose_name='embedding facial (face-api.js)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='face_embedding',
            field=models.JSONField(blank=True, default=list, help_text='Vetor de 128 floats extraído da foto via face-api.js para reconhecimento.', verbose_name='embedding facial (face-api.js)'),
        ),
    ]
