# Generated by Django 5.2.7 on 2026-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0006_credenciamentoprevio_face_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciamentoprevio',
            name='cpf',
            field=models.CharField(blank=True, help_text='Opcional. Apenas dígitos ou formato XXX.XXX.XXX-XX.', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='credenciamentoprevio',
            name='rg',
            field=models.CharField(blank=True, help_text='Opcional. Útil quando o visitante não tem CPF à mão.', max_length=20, verbose_name='RG'),
        ),
    ]
