# Generated by Django 5.2.7 on 2026-05-15 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_municipio_brasao'),
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=15, verbose_name='tipo')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em andamento'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='planejada', max_length=15, verbose_name='status')),
                ('pais', models.CharField(blank=True, help_text='País de destino. Em missões nacionais, deixar em branco ou preencher "Brasil".', max_length=100, verbose_name='país')),
                ('cidade', models.CharField(blank=True, max_length=150, verbose_name='cidade')),
                ('objetivo', models.TextField(blank=True, verbose_name='objetivo')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('relatorio_resumo', models.TextField(blank=True, help_text='Resumo executivo dos resultados da missão (documentos completos vão no repositório).', verbose_name='resumo do relatório')),
                ('chefe_delegacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missoes_como_chefe', to='cadastro.pessoa', verbose_name='chefe da delegação')),
                ('instancia_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missoes', to='instancias.instancia', verbose_name='instância vinculada')),
            ],
            options={
                'verbose_name': 'missão',
                'verbose_name_plural': 'missões',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MembroDelegacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('papel', models.CharField(choices=[('chefe', 'Chefe da delegação'), ('representante', 'Representante institucional'), ('tecnico', 'Técnico de apoio'), ('observador', 'Observador'), ('convidado', 'Convidado')], default='representante', max_length=20, verbose_name='papel na missão')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_missao', to='cadastro.pessoa', verbose_name='pessoa')),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacao', to='missoes.missao', verbose_name='missão')),
            ],
            options={
                'verbose_name': 'membro da delegação',
                'verbose_name_plural': 'membros da delegação',
                'unique_together': {('missao', 'pessoa')},
            },
        ),
    ]
