# Generated by Django 5.2.7 on 2026-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_municipio_cadastro_mu_nome_7d5b78_idx_and_more'),
        ('instancias', '0002_instancia_instancias__nome_123238_idx_and_more'),
        ('missoes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='missao',
            index=models.Index(fields=['-data_inicio'], name='missoes_mis_data_in_5c3f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='missao',
            index=models.Index(fields=['tipo'], name='missoes_mis_tipo_60d790_idx'),
        ),
        migrations.AddIndex(
            model_name='missao',
            index=models.Index(fields=['status'], name='missoes_mis_status_f50391_idx'),
        ),
    ]
