# Generated by Django 5.1.15 on 2026-03-25 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('codigo_ibge', models.IntegerField(unique=True, verbose_name='código IBGE')),
                ('populacao', models.IntegerField(default=0, verbose_name='população')),
                ('regiao', models.CharField(blank=True, choices=[('norte', 'Norte'), ('nordeste', 'Nordeste'), ('centro_oeste', 'Centro-Oeste'), ('sudeste', 'Sudeste'), ('sul', 'Sul')], max_length=20, verbose_name='região')),
                ('eh_capital', models.BooleanField(default=False, verbose_name='é capital?')),
                ('associado_fnp', models.BooleanField(default=False, verbose_name='associado FNP?')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'município',
                'verbose_name_plural': 'municípios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone (ex: heart, book)', max_length=50, verbose_name='ícone')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa?')),
            ],
            options={
                'verbose_name': 'pauta',
                'verbose_name_plural': 'pautas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('foto', models.ImageField(blank=True, upload_to='pessoas/fotos/', verbose_name='foto')),
                ('tipo', models.CharField(choices=[('interno', 'Interno'), ('prefeito', 'Prefeito(a)'), ('vice_prefeito', 'Vice-prefeito(a)'), ('secretario', 'Secretário(a)'), ('assessor', 'Assessor(a)'), ('vereador', 'Vereador(a)'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='tipo')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='cargo')),
                ('partido', models.CharField(blank=True, max_length=50, verbose_name='partido')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20, verbose_name='gênero')),
                ('redes_sociais', models.JSONField(blank=True, default=dict, help_text='Ex: {"instagram": "@prefeito", "twitter": "@prefeito"}', verbose_name='redes sociais')),
                ('biografia_curta', models.TextField(blank=True, verbose_name='biografia curta')),
                ('mandato_inicio', models.DateField(blank=True, null=True, verbose_name='início do mandato')),
                ('mandato_fim', models.DateField(blank=True, null=True, verbose_name='fim do mandato')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EnvolvimentoPauta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nivel', models.CharField(choices=[('apoiador', 'Apoiador'), ('engajado', 'Engajado'), ('lider', 'Líder')], default='apoiador', max_length=20, verbose_name='nível de envolvimento')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envolvimentos', to='cadastro.pauta', verbose_name='pauta')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envolvimentos_pauta', to='cadastro.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'envolvimento em pauta',
                'verbose_name_plural': 'envolvimentos em pautas',
                'unique_together': {('pessoa', 'pauta')},
            },
        ),
        migrations.CreateModel(
            name='VinculoMunicipio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('papel', models.CharField(choices=[('prefeito', 'Prefeito(a)'), ('vice_prefeito', 'Vice-prefeito(a)'), ('secretario', 'Secretário(a)'), ('assessor', 'Assessor(a)'), ('vereador', 'Vereador(a)'), ('contato', 'Contato')], max_length=20, verbose_name='papel')),
                ('inicio_mandato', models.DateField(blank=True, null=True, verbose_name='início do mandato')),
                ('fim_mandato', models.DateField(blank=True, null=True, verbose_name='fim do mandato')),
                ('vigente', models.BooleanField(default=True, verbose_name='vigente?')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='cadastro.municipio', verbose_name='município')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='cadastro.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'vínculo com município',
                'verbose_name_plural': 'vínculos com municípios',
                'ordering': ['-vigente', '-inicio_mandato'],
                'unique_together': {('pessoa', 'municipio', 'papel', 'inicio_mandato')},
            },
        ),
    ]
