# Generated by Django 5.1.15 on 2026-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='brasao',
            field=models.ImageField(blank=True, upload_to='municipios/brasoes/', verbose_name='brasao'),
        ),
    ]
