# Generated by Django 5.2.7 on 2026-05-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_municipio_brasao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='autorizacao_uso_imagem',
            field=models.BooleanField(default=False, help_text='Termo de autorização assinado para uso da imagem em comunicações da FNP.', verbose_name='autorização de uso de imagem'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='termo_confidencialidade',
            field=models.BooleanField(default=False, help_text='Termo de confidencialidade assinado quando aplicável à função na FNP.', verbose_name='termo de confidencialidade'),
        ),
    ]
