# Generated by Django 5.2.7 on 2026-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_pessoa_autorizacao_uso_imagem_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nome'], name='cadastro_mu_nome_7d5b78_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['uf'], name='cadastro_mu_uf_4257be_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['regiao'], name='cadastro_mu_regiao_99d5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['associado_fnp'], name='cadastro_mu_associa_91444c_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['codigo_ibge'], name='cadastro_mu_codigo__3edd73_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['nome'], name='cadastro_pe_nome_b901a0_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['tipo'], name='cadastro_pe_tipo_0a0288_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['ativo'], name='cadastro_pe_ativo_ff8988_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoa',
            index=models.Index(fields=['email'], name='cadastro_pe_email_41f9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculomunicipio',
            index=models.Index(fields=['vigente'], name='cadastro_vi_vigente_197b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculomunicipio',
            index=models.Index(fields=['pessoa', 'vigente'], name='cadastro_vi_pessoa__f4274e_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculomunicipio',
            index=models.Index(fields=['municipio', 'vigente'], name='cadastro_vi_municip_edbf38_idx'),
        ),
    ]
