# Generated by Django 5.2.7 on 2026-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_municipio_cadastro_mu_nome_7d5b78_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envolvimentopauta',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='vinculomunicipio',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
    ]
