# Generated by Django 5.2.7 on 2026-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_envolvimentopauta_arquivado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='regiao_metropolitana',
            field=models.CharField(blank=True, help_text='Nome da Região Metropolitana se o município faz parte (ex: RM de São Paulo).', max_length=80, verbose_name='região metropolitana'),
        ),
    ]
