# Generated by Django 5.2.7 on 2026-05-25 17:08

import aplicacoes.nucleo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_municipio_regiao_metropolitana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='brasao',
            field=models.ImageField(blank=True, upload_to='municipios/brasoes/', validators=[aplicacoes.nucleo.validators.validar_imagem_segura], verbose_name='brasao'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pessoas/fotos/', validators=[aplicacoes.nucleo.validators.validar_imagem_segura], verbose_name='foto'),
        ),
    ]
