# Generated by Django 5.1.15 on 2026-03-25 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEngajamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bienio_atual', models.CharField(default='2025-2026', help_text='Ex: 2025-2026', max_length=10, verbose_name='biênio atual')),
                ('meta_bienio', models.IntegerField(default=200, help_text='Pontuação bruta para atingir nota 100.', verbose_name='meta do biênio (pontos)')),
                ('fator_decaimento', models.DecimalField(decimal_places=2, default=0.7, help_text='Pontos do ano anterior são multiplicados por este fator. Ex: 0.70 = mantém 70%.', max_digits=3, verbose_name='fator de decaimento anual')),
                ('penalidade_inadimplente', models.DecimalField(decimal_places=2, default=0.3, help_text='Percentual de perda para inadimplentes. Ex: 0.30 = perde 30%.', max_digits=4, verbose_name='penalidade inadimplente (%)')),
                ('penalidade_parcial', models.DecimalField(decimal_places=2, default=0.15, help_text='Percentual de perda para adimplência parcial. Ex: 0.15 = perde 15%.', max_digits=4, verbose_name='penalidade parcial (%)')),
            ],
            options={
                'verbose_name': 'configuração de engajamento',
                'verbose_name_plural': 'configurações de engajamento',
            },
        ),
        migrations.CreateModel(
            name='Engajamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bienio', models.CharField(help_text='Ex: 2025-2026', max_length=10, verbose_name='biênio')),
                ('pontuacao_bruta', models.IntegerField(default=0, verbose_name='pontuação bruta')),
                ('pontuacao_ano_atual', models.IntegerField(default=0, verbose_name='pontos ano atual')),
                ('pontuacao_ano_anterior', models.IntegerField(default=0, verbose_name='pontos ano anterior')),
                ('penalidade_adimplencia', models.IntegerField(default=0, verbose_name='penalidade adimplência')),
                ('pontuacao_normalizada', models.IntegerField(default=0, help_text='Score final de 0 a 100.', verbose_name='pontuação normalizada (0-100)')),
                ('total_participacoes', models.IntegerField(default=0, verbose_name='total de participações')),
                ('nivel', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo'), ('inativo', 'Inativo')], default='inativo', max_length=10, verbose_name='nível')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engajamentos', to='cadastro.municipio', verbose_name='município')),
            ],
            options={
                'verbose_name': 'engajamento',
                'verbose_name_plural': 'engajamentos',
                'ordering': ['-pontuacao_normalizada'],
                'unique_together': {('municipio', 'bienio')},
            },
        ),
    ]
