# Generated by Django 5.2.7 on 2026-05-18 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoEngajamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('chave', models.CharField(choices=[('evento_presencial', 'Evento — participação presencial'), ('evento_online', 'Evento — participação online'), ('evento_bonus_palestrante', 'Evento — bônus palestrante'), ('evento_bonus_organizador', 'Evento — bônus organizador'), ('representacao_titular', 'Representação titular vigente'), ('representacao_suplente', 'Representação suplente vigente'), ('representacao_diretiva', 'Representação em função diretiva (presidência etc.)'), ('presenca_atividade', 'Presença em atividade de instância'), ('missao_internacional', 'Membro de delegação internacional'), ('missao_nacional', 'Membro de delegação nacional')], max_length=40, unique=True, verbose_name='chave')),
                ('peso', models.IntegerField(default=10, help_text='Quantos pontos esta contribuição vale, antes do decaimento e penalidades.', verbose_name='peso (pontos)')),
                ('descricao', models.TextField(blank=True, help_text='Explicação institucional do peso — aparece na página de metodologia.', verbose_name='descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo?')),
            ],
            options={
                'verbose_name': 'peso do engajamento',
                'verbose_name_plural': 'pesos do engajamento',
                'ordering': ['chave'],
            },
        ),
    ]
