# Generated by Django 5.2.7 on 2026-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engajamento', '0002_pesoengajamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesoengajamento',
            options={'ordering': ['chave', '-vigente_de'], 'verbose_name': 'peso do engajamento', 'verbose_name_plural': 'pesos do engajamento'},
        ),
        migrations.AddField(
            model_name='configuracaoengajamento',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='engajamento',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='pesoengajamento',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='pesoengajamento',
            name='vigente_ate',
            field=models.DateField(blank=True, help_text='Data até a qual este peso vale. Vazio = sem fim. Mudanças preservam histórico.', null=True, verbose_name='vigente até'),
        ),
        migrations.AddField(
            model_name='pesoengajamento',
            name='vigente_de',
            field=models.DateField(blank=True, help_text='Data a partir da qual este peso passa a valer. Vazio = sempre vigente.', null=True, verbose_name='vigente desde'),
        ),
        migrations.AlterField(
            model_name='pesoengajamento',
            name='chave',
            field=models.CharField(choices=[('evento_presencial', 'Evento — participação presencial'), ('evento_online', 'Evento — participação online'), ('evento_bonus_palestrante', 'Evento — bônus palestrante'), ('evento_bonus_organizador', 'Evento — bônus organizador'), ('representacao_titular', 'Representação titular vigente'), ('representacao_suplente', 'Representação suplente vigente'), ('representacao_diretiva', 'Representação em função diretiva (presidência etc.)'), ('presenca_atividade', 'Presença em atividade de instância'), ('missao_internacional', 'Membro de delegação internacional'), ('missao_nacional', 'Membro de delegação nacional')], max_length=40, verbose_name='chave'),
        ),
        migrations.AddIndex(
            model_name='pesoengajamento',
            index=models.Index(fields=['chave', 'ativo'], name='engajamento_chave_cb242e_idx'),
        ),
        migrations.AddIndex(
            model_name='pesoengajamento',
            index=models.Index(fields=['vigente_de', 'vigente_ate'], name='engajamento_vigente_ce2e9f_idx'),
        ),
    ]
