# Generated by Django 5.2.7 on 2026-05-18 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_envolvimentopauta_arquivado_em_and_more'),
        ('engajamento', '0003_alter_pesoengajamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotEngajamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivado_em', models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em')),
                ('bienio', models.CharField(max_length=10, verbose_name='biênio')),
                ('pontuacao_bruta', models.IntegerField(verbose_name='pontuação bruta')),
                ('pontuacao_normalizada', models.IntegerField(verbose_name='pontuação normalizada (0-100)')),
                ('nivel', models.CharField(max_length=10, verbose_name='nível')),
                ('total_participacoes', models.IntegerField(verbose_name='total de participações')),
                ('data_snapshot', models.DateField(verbose_name='data do snapshot')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_engajamento', to='cadastro.municipio')),
            ],
            options={
                'verbose_name': 'snapshot de engajamento',
                'verbose_name_plural': 'snapshots de engajamento',
                'ordering': ['-bienio', 'municipio'],
                'indexes': [models.Index(fields=['bienio'], name='engajamento_bienio_bf10a6_idx'), models.Index(fields=['municipio', 'bienio'], name='engajamento_municip_7449a4_idx')],
                'unique_together': {('municipio', 'bienio')},
            },
        ),
    ]
