# Generated by Django 5.2.7 on 2026-05-15 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_municipio_brasao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do espaço')),
                ('origem', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa'), ('evento', 'Evento')], help_text='Interna (criada pela FNP) | Externa (espaço de outro órgão) | Evento.', max_length=10, verbose_name='origem')),
                ('forma', models.CharField(choices=[('comissao', 'Comissão'), ('forum', 'Fórum'), ('com_representacao', 'Com representação'), ('sem_representacao', 'Sem representação'), ('reuniao_geral', 'Reunião Geral')], max_length=20, verbose_name='forma do espaço')),
                ('categoria', models.CharField(choices=[('principal', 'Principal'), ('secundaria', 'Secundária')], default='principal', help_text='Principal (a instância em si) | Secundária (GT, CT, subcomissão).', max_length=15, verbose_name='categoria')),
                ('tipo_arcabouco', models.CharField(blank=True, choices=[('lei_federal', 'Lei federal'), ('lei_complementar', 'Lei complementar'), ('decreto', 'Decreto'), ('portaria_ministerial', 'Portaria Ministerial'), ('portaria_interministerial', 'Portaria Interministerial'), ('regimento', 'Regimento Interno / Estatuto'), ('outro', 'Outro')], max_length=30, verbose_name='tipo do arcabouço legal')),
                ('numero_arcabouco', models.CharField(blank=True, help_text='Ex.: Lei 3434/2020, Decreto 7890/2021, Portaria 45/2024.', max_length=100, verbose_name='identificação do arcabouço')),
                ('link_arcabouco', models.URLField(blank=True, verbose_name='link do arcabouço legal')),
                ('status', models.CharField(choices=[('em_construcao', 'Em construção'), ('em_funcionamento', 'Em funcionamento'), ('inativo', 'Inativo')], default='em_funcionamento', max_length=20, verbose_name='status')),
                ('composicao', models.JSONField(blank=True, default=dict, help_text='Número de representantes por esfera. Ex.: {"federal": 2, "estadual": 3, "municipal": 5, "sociedade_civil": 2}.', verbose_name='composição')),
                ('tempo_mandato', models.CharField(blank=True, choices=[('1_ano', '1 ano'), ('2_anos', '2 anos'), ('3_anos', '3 anos'), ('4_anos', '4 anos'), ('sem_previsao', 'Sem previsão regimental')], max_length=15, verbose_name='tempo do mandato')),
                ('periodicidade_reunioes', models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('em_definicao', 'Em definição')], max_length=15, verbose_name='periodicidade das reuniões')),
                ('possui_gt_ct', models.BooleanField(default=False, help_text='Possui Grupos de Trabalho e/ou Comitês Temáticos.', verbose_name='possui GT/CT?')),
                ('link_site', models.URLField(blank=True, verbose_name='link do site')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('instancia_principal', models.ForeignKey(blank=True, help_text='Preencher quando esta for um GT/CT/subcomissão vinculada a uma instância maior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgrupos', to='instancias.instancia', verbose_name='instância principal')),
                ('ponto_focal_fnp', models.ForeignKey(blank=True, help_text='Profissional técnico da FNP responsável por apoiar e acompanhar esta instância.', limit_choices_to={'tipo': 'interno'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias_como_ponto_focal', to='cadastro.pessoa', verbose_name='ponto focal FNP')),
            ],
            options={
                'verbose_name': 'instância',
                'verbose_name_plural': 'instâncias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Representacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('funcao', models.CharField(choices=[('titular', 'Titular'), ('suplente', 'Suplente'), ('presidente', 'Presidente'), ('vice_presidente', 'Vice-presidente'), ('secretario_geral', 'Secretário(a) Geral'), ('secretario_executivo', 'Secretário(a)-Executivo(a)'), ('diretor_tematico', 'Diretor(a) Temático(a)'), ('diretor_regional', 'Diretor(a) Regional'), ('participante', 'Participante'), ('primeiro_suplente', '1º Suplente'), ('segundo_suplente', '2º Suplente')], max_length=25, verbose_name='função')),
                ('tipo_mandato', models.CharField(blank=True, choices=[('primeiro', '1º Mandato'), ('segundo', '2º Mandato'), ('reconducao', 'Recondução')], max_length=15, verbose_name='tipo de mandato')),
                ('documento_indicacao', models.CharField(blank=True, choices=[('dou', 'Publicação em DOU'), ('oficio', 'Ofício'), ('portaria', 'Portaria'), ('email', 'E-mail'), ('ata', 'Ata')], max_length=15, verbose_name='documento de indicação/nomeação')),
                ('inicio_mandato', models.DateField(blank=True, null=True, verbose_name='início do mandato')),
                ('fim_mandato', models.DateField(blank=True, null=True, verbose_name='fim do mandato')),
                ('autorizacao_uso_imagem', models.BooleanField(default=False, verbose_name='autorização do uso de imagem?')),
                ('termo_confidencialidade', models.BooleanField(default=False, verbose_name='termo de confidencialidade assinado?')),
                ('vigente', models.BooleanField(default=True, verbose_name='vigente?')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representacoes', to='instancias.instancia', verbose_name='instância')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representacoes', to='cadastro.pessoa', verbose_name='representante')),
            ],
            options={
                'verbose_name': 'representação',
                'verbose_name_plural': 'representações',
                'ordering': ['-vigente', '-inicio_mandato'],
                'unique_together': {('instancia', 'pessoa', 'funcao', 'inicio_mandato')},
            },
        ),
    ]
