# Generated by Django 5.2.7 on 2026-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_municipio_cadastro_mu_nome_7d5b78_idx_and_more'),
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instancia',
            index=models.Index(fields=['nome'], name='instancias__nome_123238_idx'),
        ),
        migrations.AddIndex(
            model_name='instancia',
            index=models.Index(fields=['origem'], name='instancias__origem_12c543_idx'),
        ),
        migrations.AddIndex(
            model_name='instancia',
            index=models.Index(fields=['status'], name='instancias__status_405078_idx'),
        ),
        migrations.AddIndex(
            model_name='instancia',
            index=models.Index(fields=['origem', 'status'], name='instancias__origem_38c60c_idx'),
        ),
        migrations.AddIndex(
            model_name='representacao',
            index=models.Index(fields=['vigente'], name='instancias__vigente_ce03eb_idx'),
        ),
        migrations.AddIndex(
            model_name='representacao',
            index=models.Index(fields=['instancia', 'vigente'], name='instancias__instanc_a3b542_idx'),
        ),
        migrations.AddIndex(
            model_name='representacao',
            index=models.Index(fields=['pessoa', 'vigente'], name='instancias__pessoa__4cbff3_idx'),
        ),
    ]
