# Generated by Django 5.2.7 on 2026-05-15 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_municipio_brasao'),
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('objetivo', models.TextField(blank=True, help_text='Resultado pretendido com a execução do projeto.', verbose_name='objetivo')),
                ('status', models.CharField(choices=[('planejamento', 'Em planejamento'), ('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=15, verbose_name='status')),
                ('fonte_recurso', models.CharField(blank=True, choices=[('proprio', 'Recurso próprio'), ('parceria', 'Parceria'), ('convenio', 'Convênio'), ('emenda', 'Emenda parlamentar'), ('internacional', 'Cooperação internacional'), ('outro', 'Outro')], max_length=15, verbose_name='fonte de recurso')),
                ('valor_orcado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='valor orçado (R$)')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('data_fim_previsto', models.DateField(blank=True, null=True, verbose_name='previsão de término')),
                ('data_fim_real', models.DateField(blank=True, null=True, verbose_name='término real')),
                ('instancia_vinculada', models.ForeignKey(blank=True, help_text='Espaço de Diálogo Federativo ao qual o projeto está relacionado, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='instancias.instancia', verbose_name='instância vinculada')),
                ('pautas', models.ManyToManyField(blank=True, related_name='projetos', to='cadastro.pauta', verbose_name='pautas relacionadas')),
                ('responsavel', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'interno'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsavel', to='cadastro.pessoa', verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['-data_inicio', 'nome'],
            },
        ),
    ]
