# Generated by Django 5.2.7 on 2026-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_municipio_cadastro_mu_nome_7d5b78_idx_and_more'),
        ('instancias', '0002_instancia_instancias__nome_123238_idx_and_more'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['status'], name='projetos_pr_status_7fdf3f_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['-data_inicio'], name='projetos_pr_data_in_193188_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['fonte_recurso'], name='projetos_pr_fonte_r_0e0da9_idx'),
        ),
    ]
