# Generated by Django 5.2.7 on 2026-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_projetos_pr_status_7fdf3f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
    ]
