# Generated by Django 5.2.7 on 2026-05-15 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(blank=True, help_text='Opcional. Se vazio, será composto a partir da instância e data.', max_length=255, verbose_name='título')),
                ('data_reuniao', models.DateField(verbose_name='data da reunião')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='horário')),
                ('formato', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida')], default='presencial', max_length=15, verbose_name='formato')),
                ('tipo_calendario', models.CharField(choices=[('ordinaria', 'Ordinária'), ('extraordinaria', 'Extraordinária')], default='ordinaria', max_length=15, verbose_name='tipo de reunião')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('adiada', 'Adiada')], default='agendada', max_length=15, verbose_name='status')),
                ('local', models.CharField(blank=True, help_text='Endereço presencial ou URL da chamada virtual.', max_length=500, verbose_name='local / link da reunião')),
                ('pauta_resumo', models.TextField(blank=True, help_text='Síntese dos itens. O documento completo vai no repositório de documentos.', verbose_name='resumo da pauta')),
                ('ata_resumo', models.TextField(blank=True, help_text='Síntese das deliberações. O documento completo vai no repositório.', verbose_name='resumo da ata')),
                ('possui_pauta', models.BooleanField(default=False, verbose_name='possui pauta registrada?')),
                ('possui_ata', models.BooleanField(default=False, verbose_name='possui ata registrada?')),
                ('possui_lista_presenca', models.BooleanField(default=False, verbose_name='possui lista de presença registrada?')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['-data_reuniao'],
            },
        ),
    ]
