# Generated by Django 5.2.7 on 2026-05-15 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='instancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='instancias.instancia', verbose_name='instância'),
        ),
    ]
