# Generated by Django 5.2.7 on 2026-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_initial'),
        ('instancias', '0002_instancia_instancias__nome_123238_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['-data_reuniao'], name='atividades__data_re_0722d5_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['instancia', '-data_reuniao'], name='atividades__instanc_7f9eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['status'], name='atividades__status_acad34_idx'),
        ),
    ]
