# Generated by Django 5.2.7 on 2026-05-15 21:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermoDicionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('termo', models.CharField(max_length=200, unique=True, verbose_name='termo')),
                ('secao', models.CharField(choices=[('instancias', 'Sobre as Instâncias'), ('representantes', 'Sobre os Representantes'), ('atividades', 'Sobre as Atividades'), ('eventos', 'Sobre os Eventos'), ('projetos', 'Sobre os Projetos'), ('missoes', 'Sobre as Missões'), ('geral', 'Geral')], default='geral', max_length=20, verbose_name='seção')),
                ('definicao', models.TextField(verbose_name='definição')),
                ('tipo_de_dado', models.CharField(blank=True, help_text='Exemplos de valores possíveis ou formato esperado.', max_length=500, verbose_name='tipo de dado / exemplos')),
                ('ordem', models.PositiveIntegerField(default=100, help_text='Menor valor aparece primeiro na seção.', verbose_name='ordem na seção')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo?')),
            ],
            options={
                'verbose_name': 'termo do dicionário',
                'verbose_name_plural': 'termos do dicionário',
                'ordering': ['secao', 'ordem', 'termo'],
            },
        ),
    ]
