# Generated by Django 5.1.15 on 2026-03-25 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criacao'), ('edicao', 'Edicao'), ('exclusao', 'Exclusao')], max_length=10, verbose_name='acao')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('objeto_id', models.CharField(max_length=50, verbose_name='ID do objeto')),
                ('objeto_repr', models.CharField(max_length=255, verbose_name='representacao')),
                ('campos_alterados', models.JSONField(blank=True, default=dict, help_text='Dicionario com campo: {antes, depois}', verbose_name='campos alterados')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_alteracao', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'log de alteracao',
                'verbose_name_plural': 'logs de alteracao',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visualizador', 'Visualizador'), ('editor', 'Editor')], default='visualizador', max_length=15, verbose_name='tipo de perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
