# Generated by Django 5.2.7 on 2026-05-18 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(help_text='Nome da URL da lista, ex. cadastro:lista_municipios.', max_length=100, verbose_name='escopo (URL name)')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('parametros', models.CharField(help_text='Query string sem o "?" inicial.', max_length=500, verbose_name='parametros (query string)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_salvos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'filtro salvo',
                'verbose_name_plural': 'filtros salvos',
                'ordering': ['escopo', 'nome'],
                'indexes': [models.Index(fields=['usuario', 'escopo'], name='nucleo_filt_usuario_df8055_idx')],
                'unique_together': {('usuario', 'escopo', 'nome')},
            },
        ),
    ]
