# Generated by Django 5.2.7 on 2026-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_filtrosalvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='permissoes_extras',
            field=models.JSONField(blank=True, default=list, help_text='Lista de slugs de permissão (ex: ["pode_importar_ibge", "pode_exportar"]).', verbose_name='permissões extras'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('visualizador', 'Visualizador'), ('editor', 'Editor'), ('admin', 'Administrador')], default='visualizador', max_length=15, verbose_name='tipo de perfil'),
        ),
    ]
