# Generated by Django 5.2.7 on 2026-05-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_envolvimentopauta_arquivado_em_and_more'),
        ('nucleo', '0003_perfil_permissoes_extras_alter_perfil_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='municipio_vinculado',
            field=models.ForeignKey(blank=True, help_text='Para perfis tipo "prefeito": qual município ele(a) pode visualizar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_vinculados', to='cadastro.municipio', verbose_name='município vinculado'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('visualizador', 'Visualizador'), ('editor', 'Editor'), ('admin', 'Administrador'), ('prefeito', 'Prefeito (portal externo)')], default='visualizador', max_length=15, verbose_name='tipo de perfil'),
        ),
    ]
