# Generated by Django 5.2.7 on 2026-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_perfil_municipio_vinculado_alter_perfil_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Identificacao amigavel — ex: "PowerBI FNP".', max_length=80, verbose_name='nome')),
                ('url', models.URLField(help_text='Endpoint HTTPS que recebera os POSTs.', verbose_name='URL de destino')),
                ('secret', models.CharField(help_text='Chave compartilhada — usada em X-FNP-Signature (HMAC-SHA256).', max_length=64, verbose_name='secret HMAC')),
                ('eventos', models.JSONField(default=list, help_text='Lista de slugs. Vazio = nenhum (subscricao desativada).', verbose_name='eventos assinados')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('ultima_entrega', models.DateTimeField(blank=True, null=True, verbose_name='ultima entrega')),
                ('ultima_falha', models.DateTimeField(blank=True, null=True, verbose_name='ultima falha')),
                ('contador_falhas', models.IntegerField(default=0, verbose_name='falhas consecutivas')),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
            },
        ),
    ]
