# Generated by Django 5.2.7 on 2026-05-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_webhooksubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='e-mail de contato')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo do pedido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em analise'), ('atendida', 'Atendida'), ('negada', 'Negada (obrigacao legal de reter)')], default='pendente', max_length=15, verbose_name='status')),
                ('resposta_dpo', models.TextField(blank=True, verbose_name='resposta do DPO')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atendido_em', models.DateTimeField(blank=True, null=True, verbose_name='atendido em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_exclusao', to=settings.AUTH_USER_MODEL, verbose_name='usuario solicitante')),
            ],
            options={
                'verbose_name': 'solicitacao de exclusao (LGPD)',
                'verbose_name_plural': 'solicitacoes de exclusao (LGPD)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AceiteTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20, verbose_name='versao do termo aceito')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP no aceite')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('aceito_em', models.DateTimeField(auto_now_add=True, verbose_name='aceito em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_termo', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'aceite de termo',
                'verbose_name_plural': 'aceites de termo',
                'ordering': ['-aceito_em'],
                'indexes': [models.Index(fields=['usuario', '-aceito_em'], name='nucleo_acei_usuario_f1dfdc_idx')],
                'unique_together': {('usuario', 'versao')},
            },
        ),
    ]
