# Generated by Django 5.2.7 on 2026-05-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_municipio_brasao_alter_pessoa_foto'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('nucleo', '0006_solicitacaoexclusao_aceitetermo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aprovado em'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='expira_em',
            field=models.DateField(blank=True, help_text='Após esta data, o login é bloqueado automaticamente.', null=True, verbose_name='expira em'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='justificativa_acesso',
            field=models.TextField(blank=True, help_text='Por que este usuário externo precisa acessar? Registrado para auditoria LGPD.', verbose_name='justificativa do acesso'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='municipios_visiveis',
            field=models.ManyToManyField(blank=True, help_text='Para perfis externos: lista de municípios que pode acessar além do vinculado.', related_name='perfis_com_acesso', to='cadastro.municipio', verbose_name='municípios visíveis (múltiplos)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='requer_2fa',
            field=models.BooleanField(default=False, help_text='Externos e admins devem ter 2FA habilitado.', verbose_name='requer 2FA?'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='status_aprovacao',
            field=models.CharField(choices=[('pendente', 'Pendente de aprovação'), ('aprovado', 'Aprovado'), ('bloqueado', 'Bloqueado'), ('expirado', 'Expirado')], default='aprovado', help_text='Externos ficam PENDENTE até DPO/admin liberar.', max_length=15, verbose_name='status de aprovação'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('visualizador', 'Visualizador'), ('editor', 'Editor'), ('admin', 'Administrador'), ('prefeito', 'Prefeito (portal externo)'), ('externo', 'Convidado externo (ACL por objeto)')], default='visualizador', max_length=15, verbose_name='tipo de perfil'),
        ),
        migrations.CreateModel(
            name='LogAcessoSensivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=80, verbose_name='modelo acessado')),
                ('objeto_id', models.CharField(max_length=50, verbose_name='id do objeto')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('contexto', models.CharField(blank=True, help_text='Ex: "detalhe_pessoa", "exportacao_csv".', max_length=50, verbose_name='contexto')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso_sensivel', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'log de acesso sensível (LGPD)',
                'verbose_name_plural': 'logs de acesso sensível (LGPD)',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['usuario', '-data'], name='nucleo_loga_usuario_f9957f_idx'), models.Index(fields=['modelo', 'objeto_id'], name='nucleo_loga_modelo_ce669c_idx'), models.Index(fields=['-data'], name='nucleo_loga_data_24098e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissaoEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(verbose_name='id do objeto')),
                ('nivel', models.CharField(choices=[('visualizar', 'Visualizar'), ('editar', 'Editar')], default='visualizar', max_length=12, verbose_name='nível')),
                ('concedido_em', models.DateTimeField(auto_now_add=True, verbose_name='concedido em')),
                ('expira_em', models.DateField(blank=True, help_text='Acesso temporário a esta entidade. Vazio = sem expiração.', null=True, verbose_name='expira em')),
                ('justificativa', models.TextField(blank=True, verbose_name='justificativa')),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissoes_concedidas', to=settings.AUTH_USER_MODEL, verbose_name='concedido por')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo da entidade')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_entidade', to='nucleo.perfil', verbose_name='perfil')),
            ],
            options={
                'verbose_name': 'permissão por entidade',
                'verbose_name_plural': 'permissões por entidade',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='nucleo_perm_content_00e383_idx'), models.Index(fields=['perfil', 'content_type'], name='nucleo_perm_perfil__bea420_idx')],
                'unique_together': {('perfil', 'content_type', 'object_id')},
            },
        ),
    ]
