# Generated by Django 5.1.15 on 2026-03-25 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('tipo', models.CharField(choices=[('reuniao_geral', 'Reunião Geral da FNP'), ('forum', 'Fórum'), ('congresso', 'Congresso'), ('viagem_internacional', 'Viagem internacional'), ('viagem_nacional', 'Viagem nacional'), ('reuniao_presencial', 'Reunião presencial na FNP'), ('reuniao_online', 'Reunião online'), ('webinar', 'Webinar'), ('presenca_fnp', 'Presença na FNP')], max_length=25, verbose_name='tipo')),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], default='presencial', max_length=15, verbose_name='modalidade')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='local')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('pontos_presencial', models.IntegerField(default=10, help_text='Pontos para participação presencial.', verbose_name='pontos (presencial)')),
                ('pontos_online', models.IntegerField(default=5, help_text='Pontos para participação online. 0 se não aplicável.', verbose_name='pontos (online)')),
                ('pontos_palestrante_bonus', models.IntegerField(default=5, help_text='Pontos extras para quem palestrou.', verbose_name='bônus palestrante')),
                ('pontos_organizador_bonus', models.IntegerField(default=5, help_text='Pontos extras para quem organizou.', verbose_name='bônus organizador')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('forma_participacao', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=15, verbose_name='forma de participação')),
                ('papel_no_evento', models.CharField(choices=[('participante', 'Participante'), ('palestrante', 'Palestrante'), ('organizador', 'Organizador(a)'), ('moderador', 'Moderador(a)')], default='participante', max_length=15, verbose_name='papel no evento')),
                ('confirmado', models.BooleanField(default=False, verbose_name='confirmado?')),
                ('pontos_calculados', models.IntegerField(default=0, help_text='Pontos atribuídos automaticamente ao salvar.', verbose_name='pontos calculados')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='data de confirmação')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='eventos.evento', verbose_name='evento')),
                ('municipio', models.ForeignKey(help_text='Município que será pontuado por esta participação.', on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='cadastro.municipio', verbose_name='município que recebe os pontos')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='cadastro.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'participação',
                'verbose_name_plural': 'participações',
                'ordering': ['-criado_em'],
                'unique_together': {('pessoa', 'evento')},
            },
        ),
    ]
