# Generated by Django 5.2.7 on 2026-05-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='acesso',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('restrito', 'Restrito'), ('gratuito', 'Gratuito'), ('inscricao_paga', 'Inscrição paga')], default='publico', max_length=20, verbose_name='acesso ao evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='instancia_vinculada',
            field=models.ForeignKey(blank=True, help_text='Espaço de Diálogo Federativo ao qual o evento está relacionado, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_vinculados', to='instancias.instancia', verbose_name='instância vinculada'),
        ),
        migrations.AddField(
            model_name='evento',
            name='natureza',
            field=models.CharField(blank=True, choices=[('deliberativo', 'Deliberativo'), ('consultivo', 'Consultivo'), ('formativo', 'Formativo')], max_length=15, verbose_name='natureza'),
        ),
        migrations.AddField(
            model_name='evento',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('articulacao_politica', 'Articulação política'), ('formacao', 'Formação / Capacitação'), ('incidencia_institucional', 'Incidência institucional'), ('tomada_decisao', 'Tomada de decisão')], max_length=30, verbose_name='objetivo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_participacao_fnp',
            field=models.CharField(blank=True, choices=[('apoio_institucional', 'Apoio Institucional'), ('realizacao', 'Realização'), ('co_realizacao', 'Co-realização'), ('patrocinador', 'Patrocinador'), ('tecnico', 'Técnico'), ('politico_institucional', 'Político-institucional')], help_text='Papel da FNP no evento (apoio, realização, patrocínio etc.).', max_length=25, verbose_name='tipo de participação da FNP'),
        ),
        migrations.AddField(
            model_name='evento',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=255, verbose_name='local (lugar)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('assembleia_geral', 'Assembléia Geral'), ('audiencia', 'Audiência'), ('comissoes', 'Comissões'), ('conferencia', 'Conferência'), ('congresso', 'Congresso'), ('grupos_trabalho', 'Grupos de Trabalho'), ('missao_internacional', 'Missão Internacional'), ('reuniao_projeto', 'Reunião de Projeto'), ('seminario', 'Seminário'), ('workshop', 'Workshop'), ('reuniao_geral', 'Reunião Geral da FNP'), ('forum', 'Fórum'), ('viagem_internacional', 'Viagem internacional'), ('viagem_nacional', 'Viagem nacional'), ('reuniao_presencial', 'Reunião presencial na FNP'), ('reuniao_online', 'Reunião online'), ('webinar', 'Webinar'), ('presenca_fnp', 'Presença na FNP')], max_length=25, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='papel_no_evento',
            field=models.CharField(choices=[('participante', 'Participante'), ('palestrante', 'Palestrante'), ('organizador', 'Organizador(a)'), ('moderador', 'Moderador(a)'), ('coordenacao', 'Coordenação'), ('expositor', 'Expositor'), ('observador', 'Observador')], default='participante', max_length=15, verbose_name='papel no evento'),
        ),
    ]
