# Generated by Django 5.2.7 on 2026-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_municipio_cadastro_mu_nome_7d5b78_idx_and_more'),
        ('eventos', '0002_evento_acesso_evento_cidade_and_more'),
        ('instancias', '0002_instancia_instancias__nome_123238_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['-data_inicio'], name='eventos_eve_data_in_8fd9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo'], name='eventos_eve_tipo_8fdb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['modalidade'], name='eventos_eve_modalid_b3a6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='participacao',
            index=models.Index(fields=['confirmado'], name='eventos_par_confirm_c58eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='participacao',
            index=models.Index(fields=['municipio', 'confirmado'], name='eventos_par_municip_21b7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='participacao',
            index=models.Index(fields=['evento', 'confirmado'], name='eventos_par_evento__a90f49_idx'),
        ),
    ]
