# Generated by Django 5.1.15 on 2026-03-25 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adimplencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ano_referencia', models.IntegerField(verbose_name='ano de referência')),
                ('status', models.CharField(choices=[('adimplente', 'Adimplente'), ('inadimplente', 'Inadimplente'), ('parcial', 'Parcial')], default='inadimplente', max_length=20, verbose_name='status')),
                ('valor_devido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor devido')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data do pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adimplencias', to='cadastro.municipio', verbose_name='município')),
            ],
            options={
                'verbose_name': 'adimplência',
                'verbose_name_plural': 'adimplências',
                'ordering': ['-ano_referencia'],
                'unique_together': {('municipio', 'ano_referencia')},
            },
        ),
    ]
