# Generated by Django 5.2.7 on 2026-05-15 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('object_id', models.UUIDField(help_text='UUID do objeto referenciado (Instância, Projeto, Missão etc.).', verbose_name='id do objeto')),
                ('nome', models.CharField(help_text='Título descritivo do documento (ex.: "Ata reunião 12/03/2026").', max_length=255, verbose_name='nome do documento')),
                ('tipo', models.CharField(choices=[('pauta', 'Pauta'), ('ata', 'Ata'), ('programacao', 'Programação'), ('lista_presenca', 'Lista de presença'), ('apresentacao', 'Apresentação'), ('relatorio', 'Relatório'), ('certificado', 'Certificado'), ('oficio', 'Ofício'), ('termo', 'Termo'), ('decreto_lei', 'Decreto / Lei / Portaria'), ('foto', 'Foto'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='tipo de documento')),
                ('arquivo', models.FileField(blank=True, help_text='Arquivo PDF, imagem ou documento de texto.', null=True, upload_to='documentos/%Y/%m/', verbose_name='arquivo')),
                ('link_externo', models.URLField(blank=True, help_text='Alternativa ao upload — URL para o documento hospedado externamente.', verbose_name='link externo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo da entidade')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documentos__content_fe825b_idx')],
            },
        ),
    ]
