# Generated by Django 5.2.7 on 2026-05-15 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='nome do template')),
                ('categoria', models.CharField(choices=[('instancias', 'Espaços de Diálogo'), ('projetos', 'Projetos'), ('missoes', 'Missões'), ('atividades', 'Atividades'), ('eventos', 'Eventos'), ('geral', 'Geral / Outros')], default='geral', help_text='Em que categoria do sistema este template fica disponível.', max_length=15, verbose_name='categoria')),
                ('assunto', models.CharField(help_text='Aceita placeholders: {{ entidade }}, {{ pessoa }}, {{ municipio }}', max_length=255, verbose_name='assunto')),
                ('corpo', models.TextField(help_text='Aceita placeholders: {{ entidade }}, {{ pessoa }}, {{ municipio }}.', verbose_name='corpo do e-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo?')),
                ('descricao', models.TextField(blank=True, help_text='Quando usar este template, observações internas.', verbose_name='descrição interna')),
            ],
            options={
                'verbose_name': 'template de e-mail',
                'verbose_name_plural': 'templates de e-mail',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('object_id', models.UUIDField(verbose_name='id do objeto')),
                ('assunto', models.CharField(help_text='Snapshot do assunto na hora do envio (sem placeholders).', max_length=255, verbose_name='assunto enviado')),
                ('corpo', models.TextField(help_text='Snapshot do corpo (sem placeholders) — para auditoria.', verbose_name='corpo enviado')),
                ('destinatarios', models.JSONField(default=list, help_text='Lista de e-mails efetivamente disparados (snapshot).', verbose_name='destinatários')),
                ('total_destinatarios', models.PositiveIntegerField(default=0, verbose_name='total de destinatários')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falha', 'Falha'), ('parcial', 'Parcial (alguns destinatários falharam)')], default='enviado', max_length=10, verbose_name='status')),
                ('erro', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo da entidade')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='comunicacao.templateemail', verbose_name='template usado')),
            ],
            options={
                'verbose_name': 'envio de e-mail',
                'verbose_name_plural': 'envios de e-mail',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='comunicacao_content_75af83_idx')],
            },
        ),
    ]
