# Generated by Django 5.2.7 on 2026-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='anexo',
            field=models.FileField(blank=True, help_text='Arquivo opcional anexado ao envio.', null=True, upload_to='envios/%Y/%m/', verbose_name='anexo'),
        ),
    ]
