# Generated by Django 5.2.7 on 2026-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0002_envio_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='templateemail',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, help_text='Marca de soft delete. Use arquivar() para esconder sem perder histórico.', null=True, verbose_name='arquivado em'),
        ),
    ]
