# Generated by Django 5.2.7 on 2026-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0003_envio_arquivado_em_templateemail_arquivado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp (link wa.me)'), ('ambos', 'E-mail + WhatsApp')], default='email', help_text='WhatsApp gera links wa.me (cliquei e envio manual); e-mail envia via SMTP.', max_length=10, verbose_name='canal de envio'),
        ),
        migrations.AddField(
            model_name='envio',
            name='links_whatsapp',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs wa.me prontas para o usuário clicar e disparar a mensagem.', verbose_name='links wa.me gerados'),
        ),
    ]
